name: 'shelfsense'
version: '1.0.0'
config-version: 2

profile: 'shelfsense'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
dispatch:
  - macro_namespace: dbt
    search_order: ['shelfsense', 'dbt']

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  shelfsense:
    staging:
      +materialized: view
      +schema: STAGING
    marts:
      +materialized: table
      +schema: MARTS
