-- ============================================================
-- ShelfSense: Snowflake initial setup
-- Run once with ACCOUNTADMIN role
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- Warehouse (use existing COMPUTE_WH or create dedicated one)
CREATE WAREHOUSE IF NOT EXISTS SHELFSENSE_WH
  WITH WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 120
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'ShelfSense compute warehouse';

-- Database
CREATE DATABASE IF NOT EXISTS SHELFSENSE;

USE DATABASE SHELFSENSE;

-- Schemas: RAW → STAGING → MARTS
CREATE SCHEMA IF NOT EXISTS RAW     COMMENT = 'Landing zone — raw VARIANT data, no transforms';
CREATE SCHEMA IF NOT EXISTS STAGING COMMENT = 'Typed, cleaned, no business logic';
CREATE SCHEMA IF NOT EXISTS MARTS   COMMENT = 'Business-ready, analytics-facing tables';

-- Role (optional; using ACCOUNTADMIN directly is fine for a personal project)
CREATE ROLE IF NOT EXISTS SHELFSENSE_ROLE;
GRANT USAGE ON WAREHOUSE SHELFSENSE_WH   TO ROLE SHELFSENSE_ROLE;
GRANT USAGE ON DATABASE  SHELFSENSE      TO ROLE SHELFSENSE_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SHELFSENSE TO ROLE SHELFSENSE_ROLE;
GRANT ALL ON ALL TABLES   IN DATABASE SHELFSENSE TO ROLE SHELFSENSE_ROLE;
GRANT ALL ON FUTURE TABLES IN DATABASE SHELFSENSE TO ROLE SHELFSENSE_ROLE;
GRANT ROLE SHELFSENSE_ROLE TO USER DARSHINILATHA2000;

SELECT CURRENT_ACCOUNT(), CURRENT_REGION(), CURRENT_USER();
